services:
  # Containers PHP-FPM
  order_app1:
    image: elessandrodev/php-core:v1.0.3
    container_name: order_app1
    working_dir: /var/www
    restart: unless-stopped
    command: php-fpm
    volumes:
      - ./:/var/www
    expose:
      - 9000
    environment:
      APP_ENV: local
      APP_DEBUG: true
    depends_on:
      order_postgres:
        condition: service_healthy
      order_redis:
        condition: service_healthy
    networks:
      - api_network

  order_app2:
    image: elessandrodev/php-core:v1.0.3
    container_name: order_app2
    working_dir: /var/www
    restart: unless-stopped
    command: php-fpm
    volumes:
      - ./:/var/www
    expose:
      - 9000
    environment:
      APP_ENV: local
      APP_DEBUG: true
    depends_on:
      order_postgres:
        condition: service_healthy
      order_redis:
        condition: service_healthy
    networks:
      - api_network

  # Horizon
  order_horizon:
    image: elessandrodev/php-core:v1.0.1
    container_name: order_horizon
    working_dir: /var/www
    restart: on-failure
    command: php artisan horizon
    volumes:
      - ./:/var/www
    environment:
      APP_ENV: local
      APP_DEBUG: true
    depends_on:
      order_redis:
        condition: service_healthy
    networks:
      - api_network

  # Scheduler
  order_scheduler:
    image: elessandrodev/php-core:v1.0.1
    container_name: order_scheduler
    working_dir: /var/www
    restart: on-failure
    command: sh -c "while true; do php artisan schedule:run --verbose --no-interaction; sleep 60; done"
    volumes:
      - ./:/var/www
    environment:
      APP_ENV: local
      APP_DEBUG: true
    depends_on:
      order_postgres:
        condition: service_healthy
      order_redis:
        condition: service_healthy
    networks:
      - api_network

  # Nginx
  order_nginx:
    image: nginx:1.25-alpine
    container_name: order_nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - order_app1
      - order_app2
    networks:
      - api_network

  # PostgreSQL
  order_postgres:
    image: postgres:16-alpine
    container_name: order_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - api_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 10s
      retries: 10

  # Redis
  order_redis:
    image: redis:7.2.4-alpine
    container_name: order_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - api_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Adminer
  order_adminer:
    image: adminer:4.8.1
    container_name: order_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - order_postgres
    networks:
      - api_network

  # SonarQube
  order_sonarqube:
    image: sonarqube:community
    container_name: order_sonarqube
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9000/api/system/status | grep -q '\"status\":\"UP\"'"]
      interval: 20s
      timeout: 10s
      retries: 20
    networks:
      - api_network

  # Sonar Scanner
  order_scanner:
    image: sonarsource/sonar-scanner-cli:5.0.1
    container_name: order_scanner
    restart: on-failure
    depends_on:
      order_sonarqube:
        condition: service_healthy
    volumes:
      - ./:/var/www
      - ./docker/sonarqube/sonar.properties:/opt/sonarqube/conf/sonar.properties
    working_dir: /usr/src
    environment:
      SONAR_HOST_URL: ${SONAR_HOST_URL}
      SONAR_LOGIN: ${SONAR_TOKEN_LOCAL}
    command: >
      sh -c "
        echo '⏳ Aguardando SonarQube...';
        until curl -s http://order_sonarqube:9000/api/system/status | grep -q '\"status\":\"UP\"'; do
          sleep 5;
        done;
        echo '✅ SonarQube pronto, rodando análise...';
        sonar-scanner \
          -Dsonar.projectKey=order-module-local \
          -Dsonar.sources=. \
          -Dsonar.php.coverage.reportPaths=tests/coverage.xml;
        echo '✅ Análise finalizada.'
      "
    networks:
      - api_network

# Networks
networks:
  api_network:
    driver: bridge

# Volumes
volumes:
  nginx_conf:
  postgres_data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
